
services:
  postgres-master:
    image: postgres:15
    container_name: postgres-master
    environment:
      POSTGRES_USER: postgres_master
      POSTGRES_PASSWORD: taqim234
      POSTGRES_DB: postgres_master
    ports:
      - "5432:5432"
    volumes:
      - postgres-master-data:/var/lib/postgresql/data
    networks:
      - postgres-network

  postgres-replica:
    image: postgres:13
    container_name: postgres-replica
    environment:
      POSTGRES_USER: postgres_replica
      POSTGRES_PASSWORD: taqim234
      POSTGRES_DB: postgres_master
    ports:
      - "5433:5432"
    volumes:
      - postgres-replica-data:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
 postgres-master-data:
 postgres-replica-data:

networks:
  postgres-network:
